name: adobe-digital-editions
version: '4.5.0'
summary: "Adobe Digital Editions under WINE"
description: "Adobe Digital Editions soaked in WINE and Snapped for Linux."

grade: stable
#confinement: strict ## switch for prod
confinement: devmode
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

environment:
  WINEARCH: "win32"
  WINEDLLOVERRIDES: "mscoree,mshtml="   # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  adobe-digital-editions:
    extensions: [ gnome-3-28 ]
    command: "bin/sommelier run-exe"
    environment:
      RUN_EXE: "C:/Program Files/Adobe/Adobe Digital Editions 4.5/DigitalEditions.exe"
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      INSTALL_URL: "https://adedownload.adobe.com/pub/adobe/digitaleditions/ADE_4.5_Installer.exe" # ade2 full setup
      TRICKS: "corefonts dotnet45 msvc100"
      VIRTDESKTOP: 0
      LC_ALL: "C.UTF-8"
      SOMMELIER_KEEP_CWD: 1  # Don't change the working directory so relative paths still work
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media
      - opengl
      - wayland
      - x11
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winetricks:
    command: bin/sommelier winetricks
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
      LC_ALL: "C.UTF-8"
    plugs:
      - network

parts:
  adobe-digital-editions:
    plugin: dump
    source: scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
      mkdir -p $SNAPCRAFT_PART_INSTALL/.wine
    organize:
      'sommelier': bin/
