name: ade2
version: '2.0.1'
summary: Adobe Digital Editions v2 under WINE
description: |
  Adobe Digital Editions v2.0.1 soaked in WINE and Snapped for Linux.

grade: stable
#confinement: strict ## switch for prod
confinement: devmode
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  ade2:
    command: |
      bin/sommelier "$(find $WINEPREFIX/ -type f -name 'DigitalEditions.exe') 2>/dev/null)"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mscoree=n;mshtml=;winemenubuilder.exe=d;*windowscodecs=n;*windowscodecsext=n;" # Prevent pop-ups about Wine Gecko
      INSTALL_URL: "http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe" # ade2 full setup
      TRICKS: "corefonts windowscodecs winxp dotnet35sp1"
      VIRTDESKTOP: 0
      LC_ALL: "C.UTF-8"
    plugs: 
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - wayland
      - wine-platform-plug
      - x11
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-platform/bin/winetricks prefix="$WINEPREFIX"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - wayland
      - x11

parts:
  ade2:
    plugin: dump
    source: scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'sommelier': bin/
